### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ineededaccount4this** [l2-/template-plugin#1]
i didnt know where i could put a suggestion.

could you add a feature to convert the combat xp drop to the amount of damage the hit is going to deal?

**Comment by l2-** [comment]
I'm not sure if that would be allowed by jagex and runelite, i don't think so. Another thing to consider is that quite a few npcs in osrs have xp multipliers making it hard to predict what the hit will be based off a xp drop. Then there's also the problem of xp being floatimg point number on the server but the client only receives floored integers leading to hit predictions off by 1 in some cases.

**Comment by tetsugoro** [comment]
If your only concern is the legality of this feature then let me tell you that calculating damage from the xp drop and displaying it is extremely unlikely to be against the rules. It's not mentioned in the most up to date disallowed 3rd party features blog and RuneLite has merged this plugin into the hub which is the same as this feature request but standalone (and incompatible): https://runelite.net/plugin-hub/show/instant-damage-calculator

I think some inaccuracy is not that big of a deal personally as the feature is really quite useful.

**Comment by l2-** [comment]
I see. I don't have motivation to make this as of right now but I will keep this in mind.

**Comment by l2-** [comment]
https://github.com/runelite/plugin-hub/pull/2300 implemented in v1.3
