### ISSUE TITLE
empty spaces in prefix/suffix cleared after session

### ISSUE THREAD

**Issue by gitrepoosrs** [l2-/template-plugin#10]
I've been adding blank spaces to the prefix and suffix to make the xp drops text a little more spaced out. It works great but after closing runelite and reopening it will truncate all the empty spaces and only leave the normal text that I had in the prefix/suffix boxes. I am trying the blank space character (ALT + 255 " ") and will let you know if that also gets removed

**Comment by l2-** [comment]
As far as i know this is only a problem if you're logged into runelite since i assume the config they save in the cloud is truncated.
