### ISSUE TITLE
Ironman predicted hit XP not working properly for PVP.

### ISSUE THREAD

**Issue by blzn42** [l2-/template-plugin#109]
As irons dont get XP from PVP the predicted hit isn't showing properly. Is there a way that this can work?

https://github.com/l2-/template-plugin/assets/174152274/e4a27651-f5ca-438c-b194-8634a0c5c0ad

**Comment by l2-** [comment]
Seems from the video that you do get xp but heavily reduced? As long as there is any hp xp drop that is consistent with the hit we can predict it. How can I reproduce this scenario? Where in game did this happen and what is the combat level of you and the opponent? And does it happen with weapons other than the voidwaker spec?

**Comment by blzn42** [comment]
It's by just hitting players in the wilderness, I was outside Spindel cave. My combat level in this new video below is 124 and my opponent was 112 don't know if that matters. 

When irons PVP they get like a fake xp drop with a block icon, so I wouldn't really know if there is a consistent XP drop for the damage dealt. Might be tough to make this work, you would know that better I think.

https://github.com/l2-/template-plugin/assets/174152274/baf0d056-0604-4d82-8d29-941b68bc61ca

**Comment by l2-** [comment]
Hmm I tested it on my own ironman just now and I can't seem to reproduce this.

>My combat level in this new video below is 124 and my opponent was 112 don't know if that matters.

Yea its not well known but xp depends on opponent combat level. So the plugin uses the combat level of the opponent to calculate the predicted hit. Although the xp you're getting is way too little regardless of enemy combat level so something else is going on here.
What is the exact type of ironman your account is? Do you know anyone who can reproduce the issue? Do you have any settings for this plugin such as filtered skills that I should try? Do you have other plugins installed that could change the amount of xp gained or are related to targetting the opponent ingame?

Could you confirm you are getting the same xp drops with vanilla xp drops? You can show vanilla and customizable at the same time by going to Customizable xp drops >Miscellaneous > turn off the hide vanilla xp drops setting

**Comment by l2-** [comment]
Are you a group ironman account? Someone told me GIM get xp but heavily reduced whereas other account types get full xp albeit fake in the case of ironman. Therefore the predicted hits in pvp for GIM will be wrong. I could adjust for this theoretically but since the xp is so heavily reduced it seems pointless. The predicted hit wouldn't be precise at all
