### ISSUE TITLE
Attach to target and not grouping xp drops bug

### ISSUE THREAD

**Issue by Steierer420** [l2-/template-plugin#110]
![XP drop bug](https://github.com/l2-/template-plugin/assets/59995870/3e95f3d1-6941-4831-b384-f5be453900ce)
When you enable attach xp drop to target and havent grouping xp drops enabled 1 xp drop fade-icon stays attached to the player and the other two icons/xp drops are attached to the target (see attachment)

**Comment by l2-** [comment]
Thanks for reporting this. It should be fixed now
