### ISSUE TITLE
xp drops stacking over eachother 

### ISSUE THREAD

**Issue by escrow11** [l2-/template-plugin#113]
![image](https://github.com/user-attachments/assets/9156fc76-6ee8-4913-9f39-619aa19b7ad0)
![image](https://github.com/user-attachments/assets/5d6f86f8-0916-4244-b0bb-c44a3d187014)

Have tried swapping around settings and issue still persists, it was working perfectly the other day until i had gotten on now, xp drops related to skilling seem to be unaffected its just the pvm hitsplats

**Comment by escrow11** [comment]
update, it only happens when enabling the never group predicted hit option, so they have to be grouped to fix this

**Comment by l2-** [comment]
Hmm this shouldn't have changed with my update yesterday. I also tried to reproduce it with the version before yesterday and the current version and found no difference in behavior. What do you for the `XP drop delay` setting? This setting controls how fast new drops can appear after each other in client ticks (=20ms). So setting this to 20 means the xp drop takes at least 400ms to show up after the predicted hit. If you have this set to 0 they will both show up at the same time and overlay

**Comment by escrow11** [comment]
thank you, i had it set to 0 but it seemed to be working perf last week, thanks for the help

**Comment by escrow11** [comment]
edit, im unable to replicate the same settings i had previously, the predicted hit would only show up on pvm mobs while the attack style xp drop would show itself over my character, now its either they overlap on an enemy or the xp drops are grouped as per image
![image](https://github.com/user-attachments/assets/fbb00114-7da0-406a-a607-00561ffb6294)

Thank you <3

**Comment by l2-** [comment]
Ah yea there was a bug where attach to target only worked for the predicted hit and hp xp drops. The rest would attach to player. I fixed this recently that's why the behaviour changed

**Comment by escrow11** [comment]
ohh i see, yea it didnt seem to be an intentional feature but i enjoyed it, thanks for the update though
