### ISSUE TITLE
Predictable hits wrong at Duke 

### ISSUE THREAD

**Issue by N0cturnalHD** [l2-/template-plugin#114]
![arclight](https://github.com/user-attachments/assets/098f16c9-fe61-4f64-b115-84014ed69d91)
![hits scythe](https://github.com/user-attachments/assets/a368f352-58a4-42a3-a1ce-61c761538144)

tried other bosses and was working fine. 

Though, ive been camping duke for a bit and they were working fine as of 7/11/24. Today they are very far off the correct hits im actually doing. pictures as examples

**Comment by l2-** [comment]
Should be fixed now
