### ISSUE TITLE
Ruby procs show the wrong predicted hit at Whisperer

### ISSUE THREAD

**Issue by IronQueenOSRS** [l2-/template-plugin#115]
Ruby procs show the wrong predicted hit at Whisperer

https://github.com/user-attachments/assets/de424682-bd81-4539-9740-ce39de4ecdbd

**Comment by hugocowan** [comment]
I would also add that predicted hits for the Whisperer using tumeken's shadow are also wrong. I can provide an example if required.

**Comment by IronQueenOSRS** [comment]
Can confirm, I was only paying attention to the ruby procs at first. the shadow exp drops also show a way lower predicted hit

**Comment by l2-** [comment]
Yea I must have messed up the xpbonus for whisperer in the last update. Thanks for bringing it to my attention

**Comment by l2-** [comment]
Should be fixed now

**Comment by IronQueenOSRS** [comment]
Thank you! I appreciate your work! I heard there was also some problem at
duke, but haven't been there myself so can't confirm this yet
