### ISSUE TITLE
Cant setup custom text

### ISSUE THREAD

**Issue by Mstarlol** [l2-/template-plugin#117]
not sure if im doing anything wrong but ive followed the advice on the main page, and i cant seem to get this to work, only getting a default text whenever i try. Ive installed the text as admin, followed the case sensitive part. some advice would be wonderful, and sorry if this isnt the right way to get advice, but im new to github.

**Comment by l2-** [comment]
Which font are you trying to use? The setting to use the font is not very user friendly but I can try to figure out why it isn't picking up your font if you link it here

**Comment by Mstarlol** [comment]
https://github.com/RuneStar/fonts

I'm trying to use the RuneScape Quill Caps font from this link. I've installed it for all users( as admin) and I've typed it out "RuneScape-Quill-Caps.otf" exactly how it shows up where I have all the fonts on my system.

**Comment by l2-** [comment]
Does it work if you type `runescape quill caps` in the plugin settings?

**Comment by Mstarlol** [comment]
I'll check it out when I get home,

**Comment by Mstarlol** [comment]
thats fixed it, thank you <3
