### ISSUE TITLE
Predicted hit on Count Draynor in NMZ seems to be 10x

### ISSUE THREAD

**Issue by dangjoeltang** [l2-/template-plugin#118]
I noticed that the predicted hit seems to be 10x the correct amount specifically on Count Draynor in NMZ hard rumble.
- using full Dharok, equipment in SS 
- actual exp amount does seem correct
- did not happen to any of the other bosses

<img width="829" alt="Screenshot 2024-07-23 at 2 32 25 PM" src="https://github.com/user-attachments/assets/588b9c51-b281-48dd-bc78-d352f8dbd80d">
<img width="882" alt="image" src="https://github.com/user-attachments/assets/e24a2979-bc32-4979-ad89-1af607148ba2">

**Comment by vftvmv2** [comment]
Adding a data point; exact same thing happens in normal rumble, full obsidian. Count Draynor only.

**Comment by Tylander732** [comment]
Appears that the value set within npcs.min.json is set incorrectly. Checking the wiki entries for Nightmare Zone Count Draynor, he should have 0% xp bonus, while his quest version has a -90% value. Then looking up the NPC id's I found that his nightmare zone versions are also set to use the -90% values.

Merge request (https://github.com/l2-/template-plugin/pull/119) should fix this

Nightmare zone versions wiki entries:
![image](https://github.com/user-attachments/assets/e06a9909-ecbc-444d-95dd-3f70f417abef)
![image](https://github.com/user-attachments/assets/4ef742ac-c541-4341-9e39-96d1e95c7a06)

Quest version wiki entry:
![image](https://github.com/user-attachments/assets/ebeea830-09b4-42e8-8623-f0cf97b6cf4a)

NPC Id's found:
![image](https://github.com/user-attachments/assets/62d7a9ff-8c17-42f5-acab-ddb933d1cc49)
