### ISSUE TITLE
Show Progress Bar

### ISSUE THREAD

**Issue by zuzx77** [l2-/template-plugin#130]
So i have download this plugin, configurate all, but when i turn on the progress bar it dont show it under the xp:
![{0950C774-D1DC-45B0-8C1C-D4849C2B6C20}](https://github.com/user-attachments/assets/725dec6d-75a5-492d-98d0-f9f211adf3eb)
help me plz?

**Comment by l2-** [comment]
Hmm not sure how this is possible. Does toggling the plugin itself off and on help? If you can find out how I can reproduce it on my computer I can take a look at it

**Comment by zuzx77** [comment]
> Hmm not sure how this is possible. Does toggling the plugin itself off and on help? If you can find out how I can reproduce it on my computer I can take a look at it

Ok this is all plugin setting so u can try again, also i disabled and enabled, installing and uninstalling the plugin and the problem still:
![{519BCBAE-6C9B-4E32-B1D7-B58A2A019E3C}](https://github.com/user-attachments/assets/08755fb6-4fd6-4340-9b14-a8cdc4338a03)
![{DFFC6308-6B96-4A63-B8FF-373BA702E922}](https://github.com/user-attachments/assets/e68ccd5e-50bd-44d3-99ef-9dc6bb50cfff)

![{C500D864-6B6A-4303-8238-9380B690E5DC}](https://github.com/user-attachments/assets/1379cd36-bafb-4bf4-b2f6-dc23aba52b3a)

![{95F903D5-C9A8-4D2A-A1B0-44FCDDA52371}](https://github.com/user-attachments/assets/f14ef354-9051-4e6e-98de-caa9f27596db)

![{3714D26C-6A31-43A4-ACBB-7179B93C0706}](https://github.com/user-attachments/assets/e28aa5d3-1fa8-4279-b400-c73c6532a9a0)


![{81394CE4-4BCE-45E3-A6D0-69063E1278F9}](https://github.com/user-attachments/assets/0096f0b7-4787-4742-943d-2be8f406ebb7)

**Comment by zuzx77** [comment]
> Hmm not sure how this is possible. Does toggling the plugin itself off and on help? If you can find out how I can reproduce it on my computer I can take a look at it

ok mate i solved, so to solved that u have to enable "XP Tracker" if other one tells u that is the SOLUTION! THX ALSO FOR SUPPORT <3 PEACE

**Comment by zuzx77** [comment]
The plugin "XP Tracker"

**Comment by l2-** [comment]
Ohhh right. yea this plugin depends on xp tracker to get the goal. Which is how it determines the bar. I forgot about that. Good find 👍
