### ISSUE TITLE
BUG: New font scaling seems to be breaking up the text

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [l2-/template-plugin#17]
Exp drop font is now somewhat garbled at certain font sizes for me? Font size 16 was fine but the number I usually have it on is garbled like in the image I've attached along with my settings.

![bugged xpdrops](https://user-images.githubusercontent.com/37377657/155897667-bb0069b2-e01b-40cd-aff3-3f851281b082.png)

**Comment by l2-** [comment]
The runescape fonts basically do not scale well at all. The default font size is 16 so setting a size that is a multiple of 16 should give good results. I don't know of a fix right now so I'll leave it as it is. You could try installing a runescape font yourself `https://github.com/RuneStar/fonts` and specifying it in the settings and see if it scales better.
