### ISSUE TITLE
Offsets from player

### ISSUE THREAD

**Issue by samanthar0se** [l2-/template-plugin#18]
Could you add the ability to configure a position offset when attached to the player?

**Comment by samanthar0se** [comment]
Another thing that could be really cool is attaching the drops to the object being interacted with, so if you're mining the drops come out of the ore rock or if you're attacking something they come out of the enemy you're attacking.

**Comment by l2-** [comment]
I like both ideas. I ll see what i can do when i have time.

**Comment by l2-** [comment]
https://github.com/runelite/plugin-hub/pull/2456

Did not add the option to attach the xp drops to skilling objects as I don't see an easy way for the client to know what skilling object you're interacting with. It is easy to tell for Actors(NPCs/Players) however so I added an option to attach xp drops to those.
