### ISSUE TITLE
Predicted hit filter option

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [l2-/template-plugin#19]
Would it be possible to add an option filters the predicted hit based on what style you are using? I would like to hide the predicted hit ffor melee since its almost always pretty instant anyway, however it would be nice to have it so the predicted hit shows up for magic and ranged since they have a potentially long delay.

**Comment by l2-** [comment]
I'll see if i can do this sometime.

**Comment by l2-** [comment]
https://github.com/runelite/plugin-hub/pull/2487
