### ISSUE TITLE
Xp drops overlap when receiving slayer xp

### ISSUE THREAD

**Issue by miikaok** [l2-/template-plugin#2]
I noticed that when killing a slayer monster on a task the slayer XP drop overlaps combat XP drop making it hard to read. I think that there is an easy solution to fix this.

Scenario:
![CUK9S3w](https://user-images.githubusercontent.com/58865894/126904595-3594ffe6-b248-4c4d-b39c-8121f49b5a1c.gif)

These are my settings on the plugin if there is something to do with them:
![TT8vOdI](https://user-images.githubusercontent.com/58865894/126904612-2ee0dd79-c263-4399-be7e-43c8aee49342.png)

**Comment by l2-** [comment]
i will look into it. i noticed it also happens on max range trident casts occasionally but your case is a lot more accessible for testing

**Comment by l2-** [comment]
Should be fixed now

**Comment by miikaok** [comment]
Seems to works perfectly on my testings. Great job!
