### ISSUE TITLE
Importing Font box

### ISSUE THREAD

**Issue by lolplayer509845** [l2-/template-plugin#22]
![image](https://user-images.githubusercontent.com/96413024/162518127-c416f5be-1aa3-428f-bbea-e6c995410392.png)
Is this "font" option box used for importing your own fonts? Does it take .ttf? Where would you navigate to put a font in if that is the case?

**Comment by l2-** [comment]
No that's were you specify the font by name. So for example to use the font times new roman you enter `times new roman` in this box. The name is case insensitive. If you have a custom font that's not part of your operating system you need to install it first before it can be picked up by the plugin when you specify its name.  See this issue if you find that you still cannot use the font after installing it https://github.com/l2-/template-plugin/issues/21
