### ISSUE TITLE
XP drops don't split

### ISSUE THREAD

**Issue by NarZook** [l2-/template-plugin#23]
Unless I am missing an option somewhere, it would be nice if there was a way to split the XP drops when training multiple skills simultaneously as opposed to simply adding them up into one number.    

**Plugin**
![XP Plugin](https://user-images.githubusercontent.com/45111338/162615531-9801d7df-02aa-4b40-ad11-b415503bf9d9.png)
**Default**
![XP Default](https://user-images.githubusercontent.com/45111338/162615533-40aafb7b-6154-48f0-9085-0d62eaf9b062.png)
.

**Comment by l2-** [comment]
The `Group XP drops` setting should be unchecked in that case.

**Comment by NarZook** [comment]
How did I miss that? Thank you! <3
Solved!
