### ISSUE TITLE
(close plz)

### ISSUE THREAD

**Issue by ruchir90** [l2-/template-plugin#26]
Fixed

**Comment by l2-** [comment]
As far as I can tell nothing should have changed. I don't think its possible to increase or reduce how bold a font is. I can only specify if it is bold or not bold. The logic for runescape fonts has changed a bit compared to earlier versions in the sense that the runescape fonts can also be customized in size and style but the logic for custom fonts has not changed.

**Comment by ruchir90** [comment]
Ah ok strange the font became bolder maybe that something on my end.
