### ISSUE TITLE
can't replace xp drops

### ISSUE THREAD

**Issue by pettrs** [l2-/template-plugin#28]
currently, both XP drops and damage are displayed. is it possible to add a feature that replaces the XP drop with the damage, similar to what the _instantdamagecalculator_ plugin does

https://user-images.githubusercontent.com/75093127/169701699-e34c65e4-95dc-4f0b-a8b3-1780c81975ea.mp4

?

**Comment by l2-** [comment]
You could add the combat skills(hitpoints, attack, strength, etc...) To filtered for xp drops so it will not show the xp drop but will show the predicted hit. Is that what you intend?
