### ISSUE TITLE
Cant move xp drops around freely.

### ISSUE THREAD

**Issue by DirtyHairy1** [l2-/template-plugin#29]
Only snaps to green boxes, was able to move around entire screen before.

**Comment by l2-** [comment]
I introduced this bug with last update to fix another positioning bug. Need to look into it. Thanks for the report.

**Comment by DirtyHairy1** [comment]
Ah okay. Atleast i know im not going crazy lol. Thanks for the reply.

**Comment by lvnd** [comment]
having this issue as well! appreciate you looking into it. the only way i've figured out how to fix it for the time being is attaching it to target/player and playing with the x/y offsets to place it where i had it previously. its a little awkward but it'll get the job done until a fix is put in :)

**Comment by l2-** [comment]
Should be fixed now. Unfortunately this overlay does not remember position when you toggle between attach and not attach and will default back to top right when set back to not attached but I didn't consider that too big of a problem.
