### ISSUE TITLE
Suggestion - "+" and "xp"

### ISSUE THREAD

**Issue by ruchir90** [l2-/template-plugin#3]
FINALLY Awesome plugin! Been waiting for ever for someone to make this.

Can you add an option to add a "+" instead of skill icon in front of the number and a "space" followed by "xp" at the end of the drop? 

So it would be "+(xpdrop) xp"
Example - https://streamable.com/u8ppz

I am trying to get my xp drops to pre eoc xp drops as they look aesthetic.

**Comment by l2-** [comment]
Yes i can look into this when i have time

**Comment by l2-** [comment]
On another note. The font used by osbuddy is lato https://fonts.google.com/specimen/Lato if you didn't know.

**Comment by ruchir90** [comment]
> Yes i can look into this when i have time

Please do I love this plugin I have it setup with the right font and "attached to play" love that option.

That clip is from Runeloader when that was a thing it had a nice exp drop option. The font I found right here is called 'Runesca[e Quill' - https://github.com/RuneStar/fonts 

 I already have the font installed look sick just waiting for "+(xpdrop) xp" option!

**Comment by ruchir90** [comment]
> Yes i can look into this when i have time

Please do I love this plugin thanks again.

That clip is from Runeloader when that was a thing. The font (its Runescape's own font) I found it here its called 'Runescape Quill' - https://github.com/RuneStar/fonts

I already have the font installed and "attached to player" option looks awesome just waiting for "+(xpdrop) xp" option!

**Comment by l2-** [comment]
Should be able to do this now with the prefix and suffix config settings
