### ISSUE TITLE
A lot of fonts aren't working

### ISSUE THREAD

**Issue by EVIGMA** [l2-/template-plugin#32]
I want this font: https://www.reddit.com/r/2007scape/comments/ojepcx/comment/h516xk9/?utm_source=share&utm_medium=web2x&context=3

But it instead gives me a default font, same case with a lot of other fonts. Ones which seems to work are Impact, Georgia, Times New Roman, Arial. Probably some others

Thanks.

**Comment by l2-** [comment]
For a font to be picked up by the plugin the name must match (but are case insensitive) and the font must have been installed system wide. The font in the reddit post works on my w10 system by entering `bankgothic` in the font setting (and setting font style to `BOLD` to reach the same effect)

**Comment by l2-** [comment]
https://github.com/l2-/template-plugin/issues/21 also see this issue.

**Comment by EVIGMA** [comment]
Thank you for all your help - appreciated
