### ISSUE TITLE
Longrange attack style incorrect recolour

### ISSUE THREAD

**Issue by robuuuste** [l2-/template-plugin#33]
Hi,

Currently, when you attack with a magic or ranged weapon on Longrange while praying melee offensive prayers (piety etc.), it will recolour the xp drop to the melee offensive prayer colour (I assume because of the defence XP). This doesn't happen on non-longrange styles. I think it should default back to the default colour when this happens, like it does on accurate and rapid attack styles.

**Comment by l2-** [comment]
Thanks for letting me know. Should be fixed with https://github.com/runelite/plugin-hub/pull/2971.
