### ISSUE TITLE
Recoloured XP drops when praying doesn't work properly

### ISSUE THREAD

**Issue by umer-rs** [l2-/template-plugin#34]
When one gets more than the combat skill's XP drop in the same game tick, the XP drop isn't recoloured.

I.E. Melee XP drop when casting a mage spell (e.g. venge), Melee XP drop when cannon fires.

**Comment by l2-** [comment]
https://github.com/l2-/template-plugin/issues/33

Basically because of this. Because of long range attacks giving defence xp i opted to to assume xp drops containing multiple combat skills will not count as melee hits. I could hoist attack and strength xp drops and then it will only be wrong for defense xp drops but i'm not sure what would be best.

**Comment by umer-rs** [comment]
Is there a method to retrieve the currently selected attack style? Can match that to the prayer instead of xp drop mayhapsingly, but this might cause a problem with manually casted spells.

https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/attackstyles/AttackStylesPlugin.java

**Comment by l2-** [comment]
https://github.com/runelite/plugin-hub/pull/3036

> Also while I'm here, is it too much effort to prebake in certain predicted hit drops for raids/bosses.
This is what https://github.com/l2-/template-plugin/blob/master/src/main/resources/com/xpdrops/npcs.min.json is for. I scraped it from the wiki and added a few bosses manually to the end such as hunleff. Content such as cox and tob is too much of a hassle to correctly predict hits as xp scales with team size. For regular bosses/npcs if the hit is not correctly predicted then its likely not in the list i just linked. In that case you can best calculate the correct xp bonus and add it to the wiki. I can update the file by scraping from the wiki or you can give me missing xpbonus multipliers directly. I rather not update every time for a single npc though.

**Comment by umer-rs** [comment]
Could help come up with formulas to compute XP multipilier for Chambers/Tob if needed, would need to keep track of party size and highest combat level in the party thought for that, and guardians would be a bit inaccurate if everyone isn't 99 mining. Something like a toggle for chambers might work though, if people want prebaked predicted hits for maxed accounts.

**Comment by l2-** [comment]
Im not willing to add such specific logic for now.
