### ISSUE TITLE
Predicted hit text not being colored when combat skills are filtered in the xp drop settings

### ISSUE THREAD

**Issue by MohamedKhaledAbdelhamid** [l2-/template-plugin#35]
This is a small, dumb and very niche issue, but it just gets the best of me due to my OCD. 

I love the predicted hit feature. The main use for combat xp drops for me was to know when I was gonna land a hit.
Now I know when I'm gonna land a hit, and 99.9% of the time I know how much exactly it will hit.

The only problem is I don't like the clutter of predicted hit + skill xp drops, so I filtered out the xp drops for combat stats.

However, this had the side effect of not coloring the predicted hit based on which combat style I'm hitting anymore.

I would love to be able to filter out combat stats xp drops, have predicted hit on and have it be recolored based on the combat style I'm using.

This would also help me know when I've correctly got my boosting prayers on, or when I accidentally forget to turn them on after they've been disabled.

I thought I might give it a shot and create a request.

Below are some images to further clarify.

![image](https://user-images.githubusercontent.com/25284866/180583157-2a1686bd-eb9c-4344-b6ca-bd52f6206052.png)

![image](https://user-images.githubusercontent.com/25284866/180583132-d6128a93-064a-4876-b3e9-34137b66f2aa.png)

**Comment by l2-** [comment]
Included in https://github.com/runelite/plugin-hub/pull/3036

**Comment by MohamedKhaledAbdelhamid** [comment]
Logging into do a gauntlet run and seeing the predicted hit text colored put the biggest smile on my face. And it was done in record time, too. Thank you so much for this!
