### ISSUE TITLE
Customizable Fonts Not Working

### ISSUE THREAD

**Issue by jwil72** [l2-/template-plugin#36]
Got multiple custom fonts and it doesn't seem to be working. I've tried all the different types of names too.

![image](https://user-images.githubusercontent.com/111310098/184701561-44e716ee-8172-42e8-820e-cdc0689784b1.png)
![image](https://user-images.githubusercontent.com/111310098/184701630-30d509d4-09af-4840-b588-2463e2ea20bd.png)
![image](https://user-images.githubusercontent.com/111310098/184701677-e162c2ec-e908-466c-93ac-de52ceeac5ad.png)

**Comment by l2-** [comment]
https://github.com/l2-/template-plugin/issues/32

Do my comments in this thread help you? I think it is the same issue.
