### ISSUE TITLE
Ungrouped Predicted Damage

### ISSUE THREAD

**Issue by QGoh** [l2-/template-plugin#37]
Hi, I've been enojoying using your customizable XP drops plugin to show predicted damage but the way predicted damage is displayed for ungrouped XP drops feels awkwardly placed. 

Would it be possible to add an option to have ungrouped XP drops displayed like this?
![](https://i.imgur.com/y8c2Iiy.png)

**Comment by l2-** [comment]
Added in https://github.com/runelite/plugin-hub/pull/3324
