### ISSUE TITLE
Xp drops broken

### ISSUE THREAD

**Issue by DirtyHairy1** [l2-/template-plugin#38]
My xp drops arent showing other than skilling drops.

**Comment by l2-** [comment]
Need more details. What are your plugin settings?

**Comment by DirtyHairy1** [comment]
![RuneLite_J7zVbvLSr8](https://user-images.githubusercontent.com/96265770/190932245-a4a3489b-2404-40b4-bd61-51db5ff2ee17.png)
![RuneLite_k7BXb58hIc](https://user-images.githubusercontent.com/96265770/190932248-56d992a7-c65c-44d2-9689-1939b5f4c475.png)

**Comment by DirtyHairy1** [comment]
not showing predicted hit

**Comment by l2-** [comment]
I see. Since you're filtering combat skills there is no xp drop to group the predicted hit with. Therefore you should turn `Never group predicted hit` ON.

**Comment by DirtyHairy1** [comment]
Thanks dood <3 fixed it. Legend
