### ISSUE TITLE
Is it possible to add a feature to hide the XP drop and display only the predicted hit?

### ISSUE THREAD

**Issue by Valachio** [l2-/template-plugin#39]
Would be very useful for pking, as you don't care about the XP drops and just want to see the hit

**Comment by l2-** [comment]
You can add the skills you do not want the xp drop for to `Skills to filter`. Make sure to turn ON `never group predicted hit` as predicted hits don't show up when the xp drop they are grouped with doesn't show up.

**Comment by Valachio** [comment]
> You can add the skills you do not want the xp drop for to `Skills to filter`. Make sure to turn ON `never group predicted hit` as predicted hits don't show up when the xp drop they are grouped with doesn't show up.

Nice. Works perfectly by adding "Attack,Strength,Hitpoints" to the skill filter. Thank you.
