### ISSUE TITLE
Xp drop not centered & Screenshot for the plugin hub

### ISSUE THREAD

**Issue by ruchir90** [l2-/template-plugin#4]
Below is an issue the suffix/prefix aren't centered they go to the right side of screen. Is there a way to fix this?
https://i.imgur.com/HxkSx0b.jpg

**Comment by ruchir90** [comment]
Ya with attached to player. Whenever you put anything in prefix/suffix the text goes to the right of the center.

Is it possible to justify the text so it spaces to the left and right evenly so the text is centered around the player's center?

**Comment by ruchir90** [comment]
> Currently the text is placed from left to right starting around the center of the character (inc prefix). The icons are placed on the left of this. With icons on the looks like its somewhat balanced

Ah ya its not that bad was just wondering if its even possible to center it with icons off.

Also can you change the xp drop example pic to this - https://i.imgur.com/Ur3CKEX.png

 It better highlights to others what this awesome plugin can do

**Comment by ruchir90** [comment]
> Currently the text is placed from left to right starting around the center of the character (inc prefix). The icons are placed on the left of this. With icons on the looks like its somewhat balanced

Ah ya its good was just wondering if its even possible to center it with icons off no big deal if you can't love it either way

Also can you change the xp drop example pic to this - https://i.imgur.com/Ur3CKEX.png
It better highlights to others what this plugin can do

**Comment by l2-** [comment]
i chose to center it on text both with icons on or off

**Comment by ruchir90** [comment]
Looks perfect now!
