### ISSUE TITLE
Suggestion: Add a "Group Combat XP drops only"

### ISSUE THREAD

**Issue by vitorebom** [l2-/template-plugin#40]
Currently the option to group xp drops is all or nothing, so if I want to group up all 4 xp drops from using DHL I also need to group the wc/fm drops when skilling with infernal axe. 
I'd like the "Group XP Drop" setting to be changed from a checkbox to a picklist between "All, combat only or skills only"

**Comment by vitorebom** [comment]
Another suggestion, for combat xp drops can I have a setting that makes it I see the damage splat on the target and the rest of the xp drop normally on top right?

**Comment by l2-** [comment]
Both suggestions require me to dissect current code paths into much more complex paths. In my opinion this case is a bit too niche to warrant such effort right now but I may consider these suggestions at some other point.
