### ISSUE TITLE
"<col=ffffff>" appended to front of string on an XP drop

### ISSUE THREAD

**Issue by RadsammyT** [l2-/template-plugin#41]
been doing my farm runs for a while when I noticed this text being appended to the xp drop, its not the text color though as any changes to that do not reflect to the appended text:
![kSQx2RkDC6](https://user-images.githubusercontent.com/32146976/197306337-94223dac-ed06-4c6a-a5d4-787f1dbfe725.png)
i have not made any changes to the plugins settings nor have I installed any plugins on RL that may conflict with this plugin. resetting RL does not make this issue go away either
and in case you want to know: here are my settings.
![CKmK03lsgg](https://user-images.githubusercontent.com/32146976/197306646-147e7e0e-238c-4466-ad13-d18c24d17a82.png)
![k5lje6DRDK](https://user-images.githubusercontent.com/32146976/197306650-acfb91e4-5716-4ae0-a6c2-2c922e5a4205.png)

**Comment by Reegal** [comment]
This is also affecting me, I reset the plugin along with an uninstall and reinstall and the issue remained.

**Comment by bvillagran** [comment]
Same thing just happened to me, I will note that I did install the https://github.com/Krazune/LineOfSight plugin right before it happened. But seems to be affecting you guys who havent changed anything

**Comment by bvillagran** [comment]
Noticed that the issue doesnt occur if I dont attach the xp drop to target or player

**Comment by ThimbleFire** [comment]
same.

**Comment by BotherSomeoneElse** [comment]
Same thing happening here. I didn't install anything else recently. Yesterday it was fine.

**Comment by Ih8graceful** [comment]
Im with everyone here, im having the same issue appear for no reason. 12 hr ago it was fine, logged in today and its displaying the <col> etc issue

**Comment by TheBradFather** [comment]
> been doing my farm runs for a while when I noticed this text being appended to the xp drop, its not the text color though as any changes to that do not reflect to the appended text: ![kSQx2RkDC6](https://user-images.githubusercontent.com/32146976/197306337-94223dac-ed06-4c6a-a5d4-787f1dbfe725.png) i have not made any changes to the plugins settings nor have I installed any plugins on RL that may conflict with this plugin. resetting RL does not make this issue go away either and in case you want to know: here are my settings. ![CKmK03lsgg](https://user-images.githubusercontent.com/32146976/197306646-147e7e0e-238c-4466-ad13-d18c24d17a82.png) ![k5lje6DRDK](https://user-images.githubusercontent.com/32146976/197306650-acfb91e4-5716-4ae0-a6c2-2c922e5a4205.png)

just wanted to post and say im also experiencing the same problem. havent changed or downloaded anything for a while and it just started happening today for me.

**Comment by LordSvegeth** [comment]
Same happening to me, tried to reinstall and didn't work; problem persist only with 'attach to player' or 'attach to target' options ON.

**Comment by l2-** [comment]
Should be fixed once https://github.com/runelite/plugin-hub/pull/3484 is merged

**Comment by LordSvegeth** [comment]
> Should be fixed once [runelite/plugin-hub#3484](https://github.com/runelite/plugin-hub/pull/3484) is merged

So what i need to do? Just wait for it? Or i have to download/install something? Newbie here :P

Thanks.

**Comment by l2-** [comment]
It has been merged. Restart your client to retrieve the latest version.

**Comment by LordSvegeth** [comment]
> It has been merged. Restart your client to retrieve the latest version.

It's working!! Thanks <3

**Comment by Reegal** [comment]
After the merge, I'm finding that when I add a prefix, the is no XP drop whatsoever
![image](https://user-images.githubusercontent.com/38463536/197368711-a29374fb-026d-4003-8904-017d760c65f5.png)
![image](https://user-images.githubusercontent.com/38463536/197368727-48dec4cb-6ebe-450c-93ff-c6cf319382ae.png)

**Comment by l2-** [comment]
Should be fixed with https://github.com/runelite/plugin-hub/pull/3486
