### ISSUE TITLE
Allow xp drops while hiding xp drops in game settings

### ISSUE THREAD

**Issue by kentor** [l2-/template-plugin#47]
So it looks like v1.5.4 of the plugin made it so that Hide XP drops in game makes this plugin hide XP drops.

I liked the behavior prior to this version where I used Hide XP drops in game to hide the progress bar, but used this plugin to show the XP drops anyway.

Can we add an option to always show XP drops no matter what the game setting is?

**Comment by l2-** [comment]
You can still do this by right clicking the xp widget ingame > Setup XP drops and then setting the Counter dropdown to off

**Comment by kentor** [comment]
ah, thanks!
