### ISSUE TITLE
Suggestion: "Hide XP drops" option for people using Hit Prediction

### ISSUE THREAD

**Issue by jarrettcommmm** [l2-/template-plugin#49]
The XP drop becomes redundant screen clutter when pking and using hit prediction, could we possibly have an option to hide XP drops when using hit prediction?  I tried setting time until disappear to 0, but this still caused it to flash occasionally, which was distracting. 

Thanks again, amazing plugin.

**Comment by l2-** [comment]
Does this https://github.com/l2-/template-plugin/issues/39 answer your question?

**Comment by jarrettcommmm** [comment]
Thank you so much, yes. Absolutely perfect plugin.
