### ISSUE TITLE
Minor issue with suffix - Runelite related perhaps?

### ISSUE THREAD

**Issue by ruchir90** [l2-/template-plugin#5]
From my testing this is something minor and it might have something to do with Runelite/programming.

The suffix is not saving the (space) in "(space)xp" and when you restart Runelite it changes back to "xp". Not a big deal I retype the (space) in front whenever I open a Runelite and its good to go.

**Comment by l2-** [comment]
This does not happen to me. I'm not logged into runelite services so my config is local. Also make sure you only have 1 client open when you change settings.

**Comment by ruchir90** [comment]
I only have 1 client open but I am logged into runelite services. It probably has to do with the services.
