### ISSUE TITLE
Skill icons not appearing when first opening the client

### ISSUE THREAD

**Issue by yerooo** [l2-/template-plugin#55]
When I open runelite and log in, whenever i get xp the skill icons don't appear until I turn the plugin off and on again.

I've tried unticking the "Allow icons override" option but the issue persists.

**Comment by l2-** [comment]
Thanks for the report. I think I know why it happens although I can't reproduce it. I can attempt to fix it sometime.

**Comment by l2-** [comment]
Hopefully fixed with https://github.com/runelite/plugin-hub/pull/3840
