### ISSUE TITLE
[SUGGESTION] Show Predicted Hit Only (Hide XP Drops Completely)

### ISSUE THREAD

**Issue by Popedigoz** [l2-/template-plugin#56]
This could be possible if you enabled a transparency slider to "Xp drop color"'s color picker, and making it 100% transparent and by unticking the "Show skill icons" option. Or there could be an option to "hide Xp drops" - however seperated from melee/mage/range xp drops prayers.

I'd like to only see xp drops with melee/mage/range prayers and always a predicted hit.

**Comment by l2-** [comment]
Following https://github.com/l2-/template-plugin/issues/39 you should be able to achieve this already

**Comment by Popedigoz** [comment]
> Following https://github.com/l2-/template-plugin/issues/39 you should be able to achieve this already

Well - yes, it _works_, **but** without the part where (as I mentioned) they'd be visible when praying melee/mage/range (Piety, Rigour, Augury, Ultimate Strength, Incredible Reflexes, Hawk Eye, etc.). Also, adding the transparency option wouldn't hurt as I'd like to tinker with it for non-combat XP drops anyways. Would be greatly appreciated.

**Comment by l2-** [comment]
O right I read over the part where you only want them visible when praying correctly

**Comment by l2-** [comment]
What about the icon though? The alpha of the icon is not controlled by the XP drop color.

**Comment by l2-** [comment]
Added in https://github.com/runelite/plugin-hub/pull/3894 but note as I said the icons do not have a transparency setting so to achieve what you want you will probably want to turn them off.

**Comment by Popedigoz** [comment]
> Added in [runelite/plugin-hub#3894](https://github.com/runelite/plugin-hub/pull/3894) but note as I said the icons do not have a transparency setting so to achieve what you want you will probably want to turn them off.

Thanks, it's now working. However, it could be even cleaner if there was a way to separate combat & non-combat XP drops. I'd like the plugin to show non-combat XP drops with icons, and correct prayer XP drops with icons.

**Comment by l2-** [comment]
Gonna need to bundle a user manual with the plugin at that point. I don't want to add settings for that for now.

**Comment by Popedigoz** [comment]
> Gonna need to bundle a user manual with the plugin at that point. I don't want to add settings for that for now.

@l2- The vanilla XP drop, can you make a toggle so that could be visible/working simultaneously with this plugin? I guess that's would allow me to get what I want without complicating the plugin.?

**Comment by Popedigoz** [comment]
@l2- Bump (sorry). What's up?

**Comment by l2-** [comment]
>  I don't want to add settings for that for now.

**Comment by l2-** [comment]
Should be possible to configure once https://github.com/runelite/plugin-hub/pull/4950 is merged
