### ISSUE TITLE
Add option to show 0 predicted hit

### ISSUE THREAD

**Issue by Jbleezy** [l2-/template-plugin#59]
It would be nice if there is a way to add a 0 hitsplat drop.

I tried to add it myself but it looks like the hitsplats are added on xp gain so I don't know how you would check for a 0 hitsplat.

**Comment by l2-** [comment]
Yea that is precisely the problem. There is no way to know so it is not possible to add currently.

**Comment by l2-** [comment]
No you don't hit every tick. If you did and you still need this feature then you might as well use visual metronome
