### ISSUE TITLE
[SUGGESTION] XP Drop color when using prayers

### ISSUE THREAD

**Issue by KhaiQ** [l2-/template-plugin#60]
Hello, could you add a feature to override the color of xp drops whenever a specific prayer is enabled (ex: piety, rigor, augury)?

**Comment by l2-** [comment]
It's in the plugin. The 'xp drop color [melee/mage/range]' settings do just that.

**Comment by KhaiQ** [comment]
Oh shoot, I must have overlooked it! Thanks for the quick reply
