### ISSUE TITLE
Bug - Horizontal XP drops don't properly follow the player (when attached to player)

### ISSUE THREAD

**Issue by Lindenk** [l2-/template-plugin#61]
Horizontal XP drops gain/lose momentum as the player moves. Since the player is always in the center of the screen though, this causes the XP to speed up or slow down instead of moving at a consistent speed.

To reproduce:
Enable "Attach to Player", set "Horizontal XP drop speed" to something noticable (maybe 150), gain exp while moving around

**Comment by l2-** [comment]
> Since the player is always in the center of the screen though
This is not true. The player is not always exactly in the center of the screen. The most obvious example is when your player is in a stalled animation. I think what you want is for the XP drop to start off using the player to screen location and then stick to screen coordinates without regard for player position however I rather keep it as it is where the location is based on the player location on screen at any moment. This does sometimes result int he effect you just described but I'm okay with that.
