### ISSUE TITLE
XP drops on left side

### ISSUE THREAD

**Issue by MistaGainz** [l2-/template-plugin#62]
Hey guys, 
Xp drops used to be in the right side , locked to the xp rectangle with progress bar like this 

![image](https://user-images.githubusercontent.com/79585508/221842394-27366428-e896-4f4e-818c-1539b16882f0.png)

But now since yesterday it just hopped to the left superrandom 

![image](https://user-images.githubusercontent.com/79585508/221842499-c58851cc-955c-47e1-9443-42ad7471f684.png)

i tried uninstalling installing reseting blabla, tried all the settings but it just stays left. 

Any idea's?

**Comment by l2-** [comment]
Did you try alt-dragging it with the mouse back into the box in the top right? Hold alt and click and drag the yellow box where the xp drops are into the cyan box under the progress bar.

**Comment by MistaGainz** [comment]
bro --' xD didnt even realise it was also a ALT box :p Tnx man! xD

**Comment by l2-** [comment]
No worries. My last update last night accidentally made the runelite client forget where the user had the xp drops anchored.
