### ISSUE TITLE
Prediction Hitsplat Not Centered

### ISSUE THREAD

**Issue by ruchir90** [l2-/template-plugin#64]
Hey its me the OG :) still using the plugin and its awesome the amount of things you've added.

I use the 'attach to player' settings and recently started using predicted hit with the 'Hitsplats' icon option. If you enable the hitsplat icon it becomes off-centered the number is perfect without any icons but once an icon is added it doesn't accommodate the new length like adding a 'prefix' does but instead goes to the left and looks "off centered".

Setting with xp drop for comparison
https://i.imgur.com/aJvP0go.jpg

Setting with using prediction alone
https://i.imgur.com/zKY73D1.png

Image shows what I mean. The number lines up perfectly but not with the Hitsplats icon. Again I am nitpicking here but just throwing this out there if its fixable awesome if no no big deal :D

**Comment by l2-** [comment]
See https://github.com/l2-/template-plugin/issues/4#issuecomment-902917452. I think is best and most consistent.

**Comment by ruchir90** [comment]
> See https://github.com/l2-/template-plugin/issues/4#issuecomment-902917452. I think is best and most consistent.

yes for sure i wrote that thread haha text centered is great thanks

**Comment by ruchir90** [comment]
> See https://github.com/l2-/template-plugin/issues/4#issuecomment-902917452. I think is best and most consistent.

Yes for sure I wrote that thread haha text centered is great but ya if changing for icon is going to ruin the rest of it its no big deal thanks you can close this issue.
