### ISSUE TITLE
Update predicted hit experience multipliers in line with new update

### ISSUE THREAD

**Issue by conn-er** [l2-/template-plugin#66]
Hi,

With the [recent bounty hunter update](https://oldschool.runescape.wiki/w/Update:Bounty_Hunter_is_Back!#Experience_Scaling_&_Rates) Jagex included some adjustments to experience multipliers for high health monsters. Because some experience multipliers have changed, the predicted hit feature now makes incorrect predictions on some of these high health bosses that were affected by the changes.

I have heard that this change affects only monsters with greater than 2,000 HP, but I wouldn't currently have any information on how exactly those multipliers have changed. This is especially troublesome for monsters like Zebak, which I believe take multiple factors other than HP into account when generating its experience multiplier.

If this is information that you are unable to easily attain, I would be willing to help collect that information. I could record short clips of me damaging the bosses that have changed so that you can use the experience drop plus the actual hit to derive the multiplier to be used in the predicted hit. I'm not sure if this strategy would work for bosses like Zebak, assuming I understand how Zebak's multiplier works.

If you need any more information from me, feel free to let me know!

**Comment by l2-** [comment]
I think it should be easy to adjust for toa and cox as the multiplier is calculated using health so i can cap the health there however for tob and all other bosses with >= 2k hp i will need new multipliers. The npcs.min.json is scraped from the wiki + a few bosses i added manually so it would be easier for me if the wiki has up to date xp multipliers
