### ISSUE TITLE
Nex predicted hits are incorrect

### ISSUE THREAD

**Issue by kylefeemster13** [l2-/template-plugin#67]
Hits are being predicted substantially lower than the actual hit. Just seems like a multiplier issue for the boss herself. All minions show correct predictions.

**Comment by l2-** [comment]
Duplicate of https://github.com/l2-/template-plugin/issues/66

I made an update but haven't submitted it to Runelite yet because I haven't tested it

**Comment by kylefeemster13** [comment]
Awesome thanks! Understand the complexity now
