### ISSUE TITLE
Gif example of XP Drop

### ISSUE THREAD

**Issue by ruchir90** [l2-/template-plugin#7]
Hey got a sick gif for xp drop example - https://i.imgur.com/QK9qekM.mp4

can you change the first image with farm patch one with this gif and also update the section on runelite so more people can see it

**Comment by Orochi88** [comment]
What font is that? Looks interesting.

**Comment by ruchir90** [comment]
> What font is that? Looks interesting.

It’s RuneScape’s own fancy font don’t but I customized it to make it bolder and bigger

**Comment by ruchir90** [comment]
> What font is that? Looks interesting.

It’s RuneScape’s other cooler font you see in game in dialogue. 

I customized it to make it bolder and bigger.

**Comment by Orochi88** [comment]
Oh really? Because I tried a couple of RS fonts, but none of them seem to work since it just uses the default font. Would you be able to share where you got the original from/the name?

**Comment by ruchir90** [comment]
> Oh really? Because I tried a couple of RS fonts, but none of them seem to work since it just uses the default font. Would you be able to share where you got the original from/the name?

You have to install the font on your computer as administrator then restart runelite and type the font name that solved it for me

You can find them online just look up “RuneScape Fonts”.  It won’t look as good as mine because I manually edited the fancy font in a font creator program to make it clearer and thicker as it was too thin. Fun little project.
