### ISSUE TITLE
xp drops centered instead of aligned to the edges? (left and right)

### ISSUE THREAD

**Issue by dogson42** [l2-/template-plugin#73]
Love the work, great plugin!

Is it possible to make the xp drops act like a centered text instead of anchoring to the right or right?

Like how the xp drops work in the middle position or like if you center text in word.

As in adding the option to do it, not making it the default of course.

**Comment by l2-** [comment]
Also discussed this in https://github.com/l2-/template-plugin/issues/53.
I don't really want to implement it right now. It works fine if you manually position it, right?

**Comment by dogson42** [comment]
It kind of works but unfortunately when xp drops are of different sizes being anchored to either left or right makes it very janky compared to how it acts when the xp drops are centered, for example when adding expected hits it can be miles off center compared to other non-combat xp drops. Making both combat and non-combat centered doesn't really work (or if using controlled/vs just one combat style) instead having to pick which one should be in the center. 

But understandable if it's too much work just a wish from my part, the plugin is incredibly good.

**Comment by l2-** [comment]
Should be possible to configure once https://github.com/runelite/plugin-hub/pull/4950 is merged
