### ISSUE TITLE
[SUGGESTION] - Hitsplat colour difference when damage is enhanced by prayer

### ISSUE THREAD

**Issue by Unlukey** [l2-/template-plugin#75]
Apologies if this is already possible. I haven't been able to configure it.

Without the plugin, when damage is enhanced by prayer, the colour of the xp drops show blue instead of white. 

This would be helpful to guage timing when prayer flicking.

Thank you!
![Xp-NoPlugin-NoPrayer](https://github.com/l2-/template-plugin/assets/142154721/78c542d1-3b29-4735-8d38-f81a9a73419f)
![Xp-NoPlugin-WithPrayer](https://github.com/l2-/template-plugin/assets/142154721/5e619184-a051-403c-99d5-dce8b97cbcea)
![Xp-WithPlugin-WithPrayer](https://github.com/l2-/template-plugin/assets/142154721/1508a55f-4b84-4255-8f4b-39201543d24c)

**Comment by l2-** [comment]
`xp drop color melee`, `xp drop color range`, `xp drop color mage` are used for this
