### ISSUE TITLE
Show predicted Hits Only

### ISSUE THREAD

**Issue by red-eye-jedi** [l2-/template-plugin#77]
currently when using the predicted hit feature it shows how much xp you earned as well, having them ungrouped does the same displaying both predicted hit + experience earned. 

Is it possible to separate these completely and have only the predicted hit displayed without showing the experience earned?
Also if seperated completely an option to not have the hitsplat icon too?

**Comment by l2-** [comment]
Does this work for you? https://github.com/l2-/template-plugin/issues/39

**Comment by red-eye-jedi** [comment]
@l2- thankyou very much, yes this is exactly what i needed.
