### ISSUE TITLE
Voidwaker spec exp not correctly showing colour

### ISSUE THREAD

**Issue by hourliedo-er** [l2-/template-plugin#80]
When using piety with voidwaker spec it doesnt highlight as a melee attack

**Comment by l2-** [comment]
Yea I don't think I'll fix this since the plugin uses equipped weapon attack style to determine what style-prayer combo is correct and it's hard/annoying to figure out if you specced with the voidwaker when the xp drop comes in

**Comment by xCholby** [comment]
damn id love to see this fixed

**Comment by l2-** [comment]
Hits while voidwaker is equipped count for both magic and melee now
