### ISSUE TITLE
Predicted hit very off

### ISSUE THREAD

**Issue by jboss94** [l2-/template-plugin#82]
For some reason, in TOA namely, if I am in a solo it operates correctly. when I scale higher it completely fails by a margin of 20+. I tried going to a fresh RL profile it still isn't working. I tried re-installing the plug-in and runelite. Im out of ideas at this point

**Comment by l2-** [comment]
Do you have a plugin that changes the party widget?
![image](https://github.com/l2-/template-plugin/assets/2605718/487c50c5-3618-4111-9bc8-d0c02f8513fb)

**Comment by jboss94** [comment]
They are the bars instead of the orbs. Could that be it? That makes sense

**Comment by jboss94** [comment]
Bars and Orbs are both within the Tombs of Amascut Plug in, would the orbs vs. bars make a difference?

**Comment by l2-** [comment]
I think it would make the difference yea. Can you try with the regular orbs and see if that fixes the problem?

**Comment by jboss94** [comment]
It seems to be good now! if other issues arise i will let you know!
