### ISSUE TITLE
Leagues IV Equilibrium Predicted Hit

### ISSUE THREAD

**Issue by Stochast1c** [l2-/template-plugin#83]
The Equilibrium relic adds a 10% of Total Level (or 20% but you can safely ignore it for complexity sake) additive xp value to all actions that grant xp and thus massively throws off the predicted hit.  Would highly appreciate either a checkbox for equilibrium (and doing the math behind the scenes) or an input for an additive value.

**Comment by l2-** [comment]
I don't really want to put logic for such niche cases in the plugin. I think you can use the xp multiplier field for this purpose although I do see how having to update the field for every total level is annoying.

**Comment by allowmoto** [comment]
I simple feature you can add is just an additive xp value for the predicted hit. Should be simple and will be nice in case other future cases arise. That way we can individually update it based on our total level.
