### ISSUE TITLE
XP drops invisible

### ISSUE THREAD

**Issue by Crystalius7** [l2-/template-plugin#86]
XP drops disappeared today. No settings were changed.

**Comment by Crystalius7** [comment]
Works in league world. But not in normal one

**Comment by Crystalius7** [comment]
I accidentally clicked the "hide xp drops" button lol...

**Comment by l2-** [comment]
For anyone with a similar problem: under miscellaneous there is a setting 'hide vanilla xp drops' that can be turned off. That way the plugin doesn't interfere with vanilla xp drops and you can troubleshoot without having to uninstall the plugin.
