### ISSUE TITLE
add option for fixed progress bar width

### ISSUE THREAD

**Issue by hballington12** [l2-/template-plugin#87]
It appears that the length of the progress bar in the xp tracker is determined by the length of the text of the current total xp. This means that the progress bar fluctuates in length according to the different digits in the total xp. I find this a bit visually annoying. Would it be possible to add an option set the bar length to a fixed length, for example based on the total number of digits in the total xp?
![Screencast from 28-11-23 11_08_49](https://github.com/l2-/template-plugin/assets/71540450/3a8bbf63-5656-47e9-8c12-42cd4fed93c8)

**Comment by l2-** [comment]
It's possible for sure but I'm not sure how the layout should be with the icon and the xp number. And how long the bar should be. You could use a monospace font so the spacing only changes when the number of digits is different (which wouldn't be the case in your example)

**Comment by hballington12** [comment]
Cheers, that works nicely.

**Comment by l2-** [comment]
This should now be fixed for every font
