### ISSUE TITLE
When changing Vertical XP drop speed the xp drop travels from further down the screen

### ISSUE THREAD

**Issue by justinbather** [l2-/template-plugin#97]
When trying to increase the speed of the xp drop vertically, it starts from further down the screen the higher the speed.

Xp drop speed at 50
![Screenshot 2024-02-16 at 10 07 32 AM](https://github.com/l2-/template-plugin/assets/118624614/cdbeae1c-d028-4d9e-a541-d2b1f79ba2ac)

Xp drop at 500
![Screenshot 2024-02-16 at 10 08 13 AM](https://github.com/l2-/template-plugin/assets/118624614/a43232c3-0baf-4a18-aa52-cd97f5daef93)

Steps for replication:
1. Set `Vertical XP drop speed` to something like 50
2. Attack something
3. Repeat with a much higher value, eg. 500

**Comment by l2-** [comment]
Yea because distance = speed * time. if you increase the speed then you have to lower the time to keep the distance the same. Unless I misunderstand you.

**Comment by justinbather** [comment]
Yeah no that's what I figured. But just thinking at least in my case. Wanted the drops to be there for less time (felt really slow) so I sped it up, but it being fast and a long travel was also weird. Mostly a UX thing

**Comment by l2-** [comment]
You expected the time to automatically adjust so the distance would stay equal? Yea I get that but programmatically changing the settings doesn't go well (in case of runelite settings panel). I would have to swap out time with distance but I feel like that's even more unintuitive for a setting. So I think I will keep this as intended behaviour

**Comment by justinbather** [comment]
No problem! When I saw it I just figured it was overlooked which is why I threw the issue up. I understand now, and it's a great project. Thank you!
